In [2]:
#Numpy operations

import numpy as np 


a = np.array([10,20,30,40])

b = np.arange(4)
b

c = a-b
c

b**2

b

a<20

#matrix multiplication

d = np.array([[1,2],[3,4]] )

e = np.array([[1,2],[5,6]])


f = d * e # element wise product

f




g = d@e # matrix multiplication 

g

h = d.dot(e)# matrix multiplication another way

h

rg = np.random.default_rng(1)

a = np.ones((2, 3), dtype=int) # creates 2 by 3 matrix with all 1s
b = rg.random((2, 3)) 
# a *= 3
# a
# b

# b+=a

b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [7]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
np.random.rand(5) 
np.random.randn(2)

np.random.randn(5,5)

np.random.randint(1,100,10)

array([88, 49, 53, 67, 20, 29, 54, 38, 78, 56])

In [6]:
arr = np.arange(0, 11)
arr

arr[8]
arr[1:5]
arr[0:5]

arr[:6]# to print till the index value



arr[0:6]

arr[5:] # start and upto end of the array

print(arr)

s_arr = arr[0:6]

s_arr[0:6] = 20

s_arr

arr

# a = [1,2,3,4,5]

# print(a)



arr

[ 0  1  2  3  4  5  6  7  8  9 10]


array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [8]:
arr = np.arange(1,11)

arr

s_arr = arr[0:6]

s_arr

s_arr[:] = 10

s_arr

arr


arr_c = arr.copy()

arr_c[:] = 100

arr_c

arr


array([10, 10, 10, 10, 10, 10,  7,  8,  9, 10])

In [9]:
arr

array([10, 10, 10, 10, 10, 10,  7,  8,  9, 10])

In [10]:
arr2d = np.zeros((10,10))

arr_length = arr2d.shape[1]

arr_length

print(type(arr_length))


for i in range(arr_length):
    arr2d[i] = i
    
arr2d

<class 'int'>


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [17]:
a = np.arange(12).reshape(3,4)
a

for row in a:
    for cell in row:
        print(cell)
        
        


        


0
1
2
3
4
5
6
7
8
9
10
11


In [23]:
#join

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),  axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

        

1
2
3
4
5
6


In [29]:
#split
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 7)

print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [32]:
# sort 

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

reversed_arr = np.flip(arr)

reversed_arr


# arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


array([[1, 0, 5],
       [4, 2, 3]])